version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
      - logger

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  logger:
    image: mendhak/http-https-echo:31
    environment:
      HTTP_PORT: 4000
    ports:
      - "4000:4000"

volumes:
  pgdata:
